saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/$',
        views.product_detail, name='product-detail'),
    url(r'^(?P<pk>[0-9]+)/publish/$', views.product_toggle_is_published,
        name='product-publish'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),
    url(r'^add/(?P<type_pk>[0-9]+)/$',
        views.product_create, name='product-add'),
    url(r'^bulk-update/$',
        views.product_bulk_update, name='product-bulk-update'),
    url(r'^add/select-type/$',
        views.product_select_type, name='product-add-select-type'),

    url(r'^types/$',
        views.product_type_list, name='product-type-list'),
    url(r'^types/add/$',
        views.product_type_create, name='product-type-add'),
    url(r'^types/(?P<pk>[0-9]+)/update/$',
        views.product_type_edit, name='product-type-update'),
    url(r'^types/(?P<pk>[0-9]+)/delete/$',
        views.product_type_delete, name='product-type-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_add, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_details, name='variant-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/update/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/images/$',
        views.variant_images, name='variant-images'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/add/$',
        views.stock_add, name='variant-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/$',
        views.stock_details, name='variant-stock-details'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/update/$',
        views.stock_edit, name='variant-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/stock/'
        r'(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='variant-stock-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/$', views.product_images,
        name='product-image-list'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_add, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/reorder/$',
        views.ajax_reorder_product_images, name='product-images-reorder'),
    url(r'^(?P<product_pk>[0-9]+)/images/upload/$',
        views.ajax_upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_detail, name='product-attribute-detail'),
    url(r'attributes/add/$',
        views.attribute_add, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/update/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/add/$',
        views.attribute_choice_value_add,
        name='product-attribute-value-add'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/update/$',  # noqa
        views.attribute_choice_value_edit,
        name='product-attribute-value-update'),
    url(r'attributes/(?P<attribute_pk>[0-9]+)/value/(?P<value_pk>[0-9]+)/delete/$',  # noqa
        views.attribute_choice_value_delete,
        name='product-attribute-value-delete'),

    url(r'stocklocations/$', views.stock_location_list,
        name='product-stock-location-list'),
    url(r'stocklocations/add/$', views.stock_location_add,
        name='product-stock-location-add'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/$', views.stock_location_edit,
        name='product-stock-location-edit'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/delete/$',
        views.stock_location_delete, name='product-stock-location-delete'),

    url(r'^ajax/variants/$',
        views.ajax_available_variants_list, name='ajax-available-variants'),
    url(r'^ajax/products/$',
        views.ajax_products_list, name='ajax-products')]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from graphene_django.views import GraphQLView

from .account.urls import urlpatterns as account_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social'))]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/product/product_attribute/values/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% if attribute.pk %}
   {% trans "Edit" context "Dashboard attributes list" %} - {{ attribute }}
  {% else %}
    {% trans "Add new attribute" context "Attribute detail page title" %}
  {% endif %}
  - {{ block.super }}
{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block menu_attributes_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:product-attributes" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}


{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url 'dashboard:product-attributes' %}" class="breadcrumbs--ellipsed-item">
        {% trans "Attributes" context "Dashboard attributes list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url 'dashboard:product-attributes' %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    {% if attribute.pk %}
    <li>
      <a href="{% url 'dashboard:product-attribute-detail' attribute.pk %}" class="breadcrumbs--ellipsed-item">
        {{ attribute }}
      </a>
    </li>
    {% endif %}
    {% if value.pk %}
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Edit" context "Attribute detail breadcrumbs" %}
      </span>
    </li>
    {% else %}
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Add new attribute" context "Attribute detail breadcrumbs" %}
      </span>
    </li>
    {% endif %}
  </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l9">
      <div class="card">
        <form method="post" enctype="multipart/form-data" id="form-attributes" novalidate>
          {% csrf_token %}
          <div class="card-content">
            <span class="card-title">
              {% trans "Attribute values" context "Attribute values form title" %}
            </span>
            <div class="row">
              {{ form|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            {% if value.pk %}
              <a href="{% url 'dashboard:product-attribute-detail' pk=attribute.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Save" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:product-attribute-detail' pk=attribute.pk%}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% endblock %}