saleor/account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_views

from . import views

urlpatterns = [
    url(r'^$', views.details, name='details'),

    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^password/reset/$', views.password_reset,
        name='reset-password'),
    url(r'^password/reset/done/$', django_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'),
        name='reset-password-done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',  # noqa
        views.password_reset_confirm, name='reset-password-confirm'),
    url(r'password/reset/complete/$', django_views.PasswordResetCompleteView.as_view(  # noqa
        template_name='account/password_reset_from_key_done.html'),
        name='reset-password-complete'),

    url(r'^address/(?P<pk>\d+)/edit/$', views.address_edit,
        name='address-edit'),
    url(r'^address/(?P<pk>\d+)/delete/$',
        views.address_delete, name='address-delete'),
]

saleor/cart/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/(?P<variant_id>\d+)/$', views.update, name='update-line'),
    url(r'^summary/$', views.summary, name='cart-summary'),
    url(r'^shipingoptions/$', views.get_shipping_options,
        name='shipping-options')]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from graphene_django.views import GraphQLView

from .account.urls import urlpatterns as account_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social'))]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/cart/forms.py
"""Cart-related forms and fields."""
from django import forms
from django.conf import settings
from django.core.exceptions import NON_FIELD_ERRORS, ObjectDoesNotExist
from django.utils.translation import npgettext_lazy, pgettext_lazy
from django_countries.fields import LazyTypedChoiceField, countries

from ..core.exceptions import InsufficientStock
from ..shipping.utils import get_shipment_options


class QuantityField(forms.IntegerField):
    """A specialized integer field with initial quantity and min/max values."""

    def __init__(self, **kwargs):
        super().__init__(
            min_value=0, max_value=settings.MAX_CART_LINE_QUANTITY,
            initial=1, **kwargs)


class AddToCartForm(forms.Form):
    """Add-to-cart form.

    Allows selection of a product variant and quantity.

    The save method adds it to the cart.
    """

    quantity = QuantityField(
        label=pgettext_lazy('Add to cart form field label', 'Quantity'))
    error_messages = {
        'not-available': pgettext_lazy(
            'Add to cart form error',
            'Sorry. This product is currently not available.'),
        'empty-stock': pgettext_lazy(
            'Add to cart form error',
            'Sorry. This product is currently out of stock.'),
        'variant-does-not-exists': pgettext_lazy(
            'Add to cart form error',
            'Oops. We could not find that product.'),
        'insufficient-stock': npgettext_lazy(
            'Add to cart form error',
            'Only %d remaining in stock.',
            'Only %d remaining in stock.')}

    def __init__(self, *args, **kwargs):
        self.cart = kwargs.pop('cart')
        self.product = kwargs.pop('product')
        self.discounts = kwargs.pop('discounts', ())
        super().__init__(*args, **kwargs)

    def clean(self):
        """Clean the form.

        Makes sure the total quantity in cart (taking into account what was
        already there) does not exceed available quantity.
        """
        cleaned_data = super().clean()
        quantity = cleaned_data.get('quantity')
        if quantity is None:
            return cleaned_data
        try:
            product_variant = self.get_variant(cleaned_data)
        except ObjectDoesNotExist:
            msg = self.error_messages['variant-does-not-exists']
            self.add_error(NON_FIELD_ERRORS, msg)
        else:
            cart_line = self.cart.get_line(product_variant)
            used_quantity = cart_line.quantity if cart_line else 0
            new_quantity = quantity + used_quantity
            try:
                product_variant.check_quantity(new_quantity)
            except InsufficientStock as e:
                remaining = e.item.get_stock_quantity() - used_quantity
                if remaining:
                    msg = self.error_messages['insufficient-stock']
                    self.add_error('quantity', msg % remaining)
                else:
                    msg = self.error_messages['empty-stock']
                    self.add_error('quantity', msg)
        return cleaned_data

    def save(self):
        """Add the selected product variant and quantity to the cart."""
        product_variant = self.get_variant(self.cleaned_data)
        return self.cart.add(variant=product_variant,
                             quantity=self.cleaned_data['quantity'])

    def get_variant(self, cleaned_data):
        """Return a product variant that matches submitted values.

        This allows specialized implementations to select the variant based on
        multiple fields (like size and color) instead of having a single
        variant selection widget.
        """
        raise NotImplementedError()


class ReplaceCartLineForm(AddToCartForm):
    """Replace quantity in cart form.

    Similar to AddToCartForm but its save method replaces the quantity.
    """

    def __init__(self, *args, **kwargs):
        self.variant = kwargs.pop('variant')
        kwargs['product'] = self.variant.product
        super().__init__(*args, **kwargs)
        self.cart_line = self.cart.get_line(self.variant)
        self.fields['quantity'].widget.attrs = {
            'min': 1, 'max': settings.MAX_CART_LINE_QUANTITY}

    def clean_quantity(self):
        """Clean the quantity field.

        Checks if target quantity does not exceed the currently available
        quantity.
        """
        quantity = self.cleaned_data['quantity']
        try:
            self.variant.check_quantity(quantity)
        except InsufficientStock as e:
            msg = self.error_messages['insufficient-stock']
            raise forms.ValidationError(
                msg % e.item.get_stock_quantity())
        return quantity

    def clean(self):
        """Clean the form skipping the add-to-form checks."""
        # explicitly skip parent's implementation
        # pylint: disable=E1003
        return super(AddToCartForm, self).clean()

    def get_variant(self, cleaned_data):
        """Return the matching variant.

        In this case we explicitly know the variant as we're modifying an
        existing line in cart.
        """
        return self.variant

    def save(self):
        """Replace the selected product's quantity in cart."""
        product_variant = self.get_variant(self.cleaned_data)
        return self.cart.add(product_variant, self.cleaned_data['quantity'],
                             replace=True)


class CountryForm(forms.Form):
    """Country selection form."""

    country = LazyTypedChoiceField(
        label=pgettext_lazy('Country form field label', 'Country'),
        choices=countries)

    def get_shipment_options(self):
        """Return a list of shipping methods for the selected country."""
        code = self.cleaned_data['country']
        return get_shipment_options(code)

saleor/cart/views.py
"""Cart-related views."""
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.template.response import TemplateResponse
from django.urls import reverse
from django_babel.templatetags.babel import currencyfmt

from ..core.utils import get_user_shipping_country, to_local_currency
from ..product.models import ProductVariant
from ..shipping.utils import get_shipment_options
from .forms import CountryForm, ReplaceCartLineForm
from .models import Cart
from .utils import (
    check_product_availability_and_warn, get_cart_data, get_or_empty_db_cart)


@get_or_empty_db_cart(cart_queryset=Cart.objects.for_display())
def index(request, cart):
    """Display cart details."""
    discounts = request.discounts
    cart_lines = []
    check_product_availability_and_warn(request, cart)

    # refresh required to get updated cart lines and it's quantity
    try:
        cart = Cart.objects.get(pk=cart.pk)
    except Cart.DoesNotExist:
        pass

    for line in cart.lines.all():
        initial = {'quantity': line.quantity}
        form = ReplaceCartLineForm(None, cart=cart, variant=line.variant,
                                   initial=initial, discounts=discounts)
        cart_lines.append({
            'variant': line.variant,
            'get_price_per_item': line.get_price_per_item(discounts),
            'get_total': line.get_total(discounts=discounts),
            'form': form})

    default_country = get_user_shipping_country(request)
    country_form = CountryForm(initial={'country': default_country})
    default_country_options = get_shipment_options(default_country)

    cart_data = get_cart_data(
        cart, default_country_options, request.currency, request.discounts)
    ctx = {
        'cart_lines': cart_lines,
        'country_form': country_form,
        'default_country_options': default_country_options}
    ctx.update(cart_data)

    return TemplateResponse(
        request, 'cart/index.html', ctx)


@get_or_empty_db_cart(cart_queryset=Cart.objects.for_display())
def get_shipping_options(request, cart):
    """Display shipping options to get a price estimate."""
    country_form = CountryForm(request.POST or None)
    if country_form.is_valid():
        shipments = country_form.get_shipment_options()
    else:
        shipments = None
    ctx = {
        'default_country_options': shipments,
        'country_form': country_form}
    cart_data = get_cart_data(
        cart, shipments, request.currency, request.discounts)
    ctx.update(cart_data)
    return TemplateResponse(
        request, 'cart/_subtotal_table.html', ctx)


@get_or_empty_db_cart()
def update(request, cart, variant_id):
    """Update the line quantities."""
    if not request.is_ajax():
        return redirect('cart:index')
    variant = get_object_or_404(ProductVariant, pk=variant_id)
    discounts = request.discounts
    status = None
    form = ReplaceCartLineForm(
        request.POST, cart=cart, variant=variant, discounts=discounts)
    if form.is_valid():
        form.save()
        response = {
            'variantId': variant_id,
            'subtotal': 0,
            'total': 0,
            'cart': {
                'numItems': cart.quantity,
                'numLines': len(cart)}}
        updated_line = cart.get_line(form.cart_line.variant)
        if updated_line:
            response['subtotal'] = currencyfmt(
                updated_line.get_total(discounts=discounts).gross,
                updated_line.get_total(discounts=discounts).currency)
        if cart:
            cart_total = cart.get_total(discounts=discounts)
            response['total'] = currencyfmt(
                cart_total.gross, cart_total.currency)
            local_cart_total = to_local_currency(cart_total, request.currency)
            if local_cart_total:
                response['localTotal'] = currencyfmt(
                    local_cart_total.gross, local_cart_total.currency)
        status = 200
    elif request.POST is not None:
        response = {'error': form.errors}
        status = 400
    return JsonResponse(response, status=status)


@get_or_empty_db_cart(cart_queryset=Cart.objects.for_display())
def summary(request, cart):
    """Display a cart summary suitable for displaying on all pages."""
    def prepare_line_data(line):
        product_type = line.variant.product.product_type
        attributes = product_type.variant_attributes.all()
        first_image = line.variant.get_first_image()
        price_per_item = line.get_price_per_item(discounts=request.discounts)
        line_total = line.get_total(discounts=request.discounts)
        return {
            'product': line.variant.product,
            'variant': line.variant.name,
            'quantity': line.quantity,
            'attributes': line.variant.display_variant_attributes(attributes),
            'image': first_image,
            'price_per_item': currencyfmt(
                price_per_item.gross, price_per_item.currency),
            'line_total': currencyfmt(line_total.gross, line_total.currency),
            'update_url': reverse(
                'cart:update-line', kwargs={'variant_id': line.variant_id}),
            'variant_url': line.variant.get_absolute_url()}
    if cart.quantity == 0:
        data = {'quantity': 0}
    else:
        cart_total = cart.get_total(discounts=request.discounts)
        data = {
            'quantity': cart.quantity,
            'total': currencyfmt(cart_total.gross, cart_total.currency),
            'lines': [prepare_line_data(line) for line in cart.lines.all()]}

    return render(request, 'cart_dropdown.html', data)

templates/cart/_subtotal_table.html
{% load i18n %}
{% load price_range from price_ranges %}
{% load gross from prices_i18n %}

{% if shipping_required %}
  <div class="table__row">
    <div class="row">
      <div class="col-8 cart__total__subtotal">
        <h3>{% trans "Subtotal" context "Order subtotal" %}</h3>
      </div>
      <div class="col-4">
        <h3 class="text-right cart-subtotal" data-value="{% gross cart_total %}" {% if local_cart_total %}data-value-local="{% gross local_cart_total %}"{% endif %}>
          {% spaceless %}
            {% gross cart_total html=True %}
            {% if local_cart_total %}
              <br>
              <small>
                &asymp;
                {% gross local_cart_total html=True %}
              </small>
            {% endif %}
          {% endspaceless %}
        </h3>
      </div>
    </div>
  </div>
  <div class="last table__row cart__delivery-info">
    <div class="row">
      <div class="col-7 cart__total__subtotal deliveryform" data-csrf="{{ csrf_token }}">
        <div class="row">
          <div class="col-12 col-md-4">
            <p>{% trans "Shipping cost for:" context "Cart shipping cost form" %}</p>
          </div>
          <div class="col-12 col-md-8">
            {{ country_form.country }}
          </div>
        </div>
      </div>
      <div class="col-5">
        <div class="row">
          <div class="col-md-12 col-12 text-right">
            <p class="cart__delivery-info__price">
              {% if default_country_options %}
                {% price_range default_country_options %}
              {% endif %}
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endif %}
<div class="cart__total">
  <div class="row">
    <div class="col-8 cart__total__subtotal">
      <h3>{% trans "Total" context "Order subtotal" %}</h3>
    </div>
    <div class="col-4">
      {% spaceless %}
        <h3 class="text-right cart-total"><span>{% price_range total_with_shipping %}</span>
          {% if local_total_with_shipping %}
            <br>
            <small>
              &asymp;
              {% price_range local_total_with_shipping %}
            </small>
          {% endif %}
        </h3>
      {% endspaceless %}
    </div>
  </div>
</div>

templates/cart/index.html
{% extends "base.html" %}
{% load gross from prices_i18n %}
{% load i18n %}
{% load staticfiles %}
{% load get_thumbnail from product_images %}

{% block title %}{% trans "Your cart" context "Cart page title" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
  <ul class="breadcrumbs list-unstyled">
    <li><a href="{% url 'home' %}">{% trans "Home" context "Main navigation item" %}</a></li>
    <li><a rel="nofollow" href="{% url 'cart:index' %}">{% trans "Cart" context "Cart breadcrumb" %}</a></li>
  </ul>
{% endblock breadcrumb %}

{% block meta_tags %}
  <meta name="robots" content="nofollow">
{% endblock meta_tags %}

{% block content %}
  <div class="alert alert-success remove-product-alert d-none">
    {% trans "Product has been removed from cart" context "Cart message" %}
    <button type="button" class="close close-msg" aria-hidden="true">&times;</button>
  </div>
  <div class="cart">
    {% if cart_lines %}
      <div class="table__header d-none d-md-block">
        <div class="row">
          <div class="col-md-7">
            <small>{% trans "Product" context "Cart table header" %}</small>
          </div>
          <div class="col-md-3">
            <small>{% trans "Quantity" context "Cart table header" %}</small>
          </div>
          <div class="col-md-2 text-right">
            <small>{% trans "Price" context "Cart table header" %}</small>
          </div>
        </div>
      </div>
      {% for line in cart_lines %}
        <div class="cart__line{% if forloop.last %} last{% endif %} table__row">
          <div class="row">
            <div class="col-7 cart__line__product">
              <a class="link--clean" href="{{ line.variant.get_absolute_url }}">
                <img class="lazyload lazypreload" data-src="{% get_thumbnail line.variant.product.images.first.image method="crop" size="60x60" %}"
                     data-srcset="{% get_thumbnail line.variant.product.images.first.image method="crop" size="60x60" %} 1x, {% get_thumbnail line.variant.product.images.first.image method="crop" size="120x120" %} 2x"
                     alt="">
                <p>{{ line.variant.product }}<br><small>{{ line.variant }}</small></p>
              </a>
            </div>
            <div class="col-5">
              <div class="row">
                <div class="cart__line__quantity col-md-7 col-12">
                  <form role="form" action="{% url "cart:update-line" variant_id=line.variant.pk %}" method="post" class="form-cart">
                    <div class="{% if form.quantity.errors %} has-error{% endif %}" tabindex="-1">
                      {{ line.form.quantity }}
                    </div>
                    {% csrf_token %}
                  </form>
                  <span class="cart-item-delete">
                    <svg data-src="{% static "images/delete.svg" %}" height="20px" width="20px" />
                  </span>
                  <small class="cart__line__quantity-error text-danger"></small>
                </div>
                <div class="cart-item-price col-md-5 col-12" data-product-id="{{ line.variant.pk }}">
                  <p class="text-right">{% gross line.get_total html=True %}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      <div class="cart__subtotal">
        {% include 'cart/_subtotal_table.html' %}
      </div>
      <div class="row">
        <div class="col-md-12">
          <a href="{% url "checkout:login" %}" class="btn primary float-right cart__submit">
            {% trans "Checkout" context "Cart primary action" %}
          </a>
        </div>
      </div>
    {% else %}
      <div class="cart__empty">
        <img class="lazyload lazypreload" data-src="{% static 'images/empty-cart-bg.png' %}" data-srcset="{% static 'images/empty-cart-bg.png' %} 1x, {% static 'images/empty-cart-bg2x.png' %} 2x">
        <h2>{% trans "There are no products in your shopping cart." context "Empty cart message" %}</h2>
        <a href="{% url 'home' %}" class="btn primary">{% trans "Check out our sales" context "Empty cart link" %}</a>
      </div>
    {% endif %}
  </div>
{% endblock content %}