saleor/dashboard/customer/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.customer_list, name='customers'),
    url(r'^create/$', views.customer_create, name='customer-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.customer_details, name='customer-details'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.customer_edit,
        name='customer-update')]

saleor/dashboard/group/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.group_list, name='group-list'),
    url(r'^group-create/$', views.group_create, name='group-create'),
    url(r'^(?P<pk>[0-9]+)/$', views.group_details, name='group-details'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.group_delete, name='group-delete')]

saleor/dashboard/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.order_list, name='orders'),
    url(r'^(?P<order_pk>\d+)/$',
        views.order_details, name='order-details'),
    url(r'^(?P<order_pk>\d+)/add-note/$',
        views.order_add_note, name='order-add-note'),
    url(r'^(?P<order_pk>\d+)/cancel/$',
        views.cancel_order, name='order-cancel'),
    url(r'^(?P<order_pk>\d+)/address/(?P<address_type>billing|shipping)/$',
        views.address_view, name='address-edit'),

    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/capture/$',
        views.capture_payment, name='capture-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/release/$',
        views.release_payment, name='release-payment'),
    url(r'^(?P<order_pk>\d+)/payment/(?P<payment_pk>\d+)/refund/$',
        views.refund_payment, name='refund-payment'),

    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change/$',
        views.orderline_change_quantity, name='orderline-change-quantity'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/split/$',
        views.orderline_split, name='orderline-split'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/cancel/$',
        views.orderline_cancel, name='orderline-cancel'),
    url(r'^(?P<order_pk>\d+)/line/(?P<line_pk>\d+)/change-stock/$',
        views.orderline_change_stock, name='orderline-change-stock'),
    url(r'^(?P<order_pk>\d+)/remove-voucher/$',
        views.remove_order_voucher, name='order-remove-voucher'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/ship/$',
        views.ship_delivery_group, name='ship-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/cancel/$',
        views.cancel_delivery_group, name='cancel-delivery-group'),
    url(r'^(?P<order_pk>\d+)/shipment/(?P<group_pk>\d+)/add-variant/$',
        views.add_variant_to_group, name='add-variant-to-group'),
    url(r'^(?P<order_pk>\d+)/invoice/$',
        views.order_invoice, name='order-invoice'),
    url(r'^(?P<group_pk>\d+)/packing-slips/$',
        views.order_packing_slip, name='order-packing-slips')]

saleor/dashboard/urls.py
from django.conf.urls import include, url

from . import views as core_views
from .category.urls import urlpatterns as category_urls
from .collection.urls import urlpatterns as collection_urls
from .customer.urls import urlpatterns as customer_urls
from .discount.urls import urlpatterns as discount_urls
from .group.urls import urlpatterns as groups_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls
from .shipping.urls import urlpatterns as shipping_urls
from .sites.urls import urlpatterns as site_urls
from .staff.urls import urlpatterns as staff_urls

urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^categories/', include(category_urls)),
    url(r'^collections/', include(collection_urls)),
    url(r'^orders/', include(order_urls)),
    url(r'^products/', include(product_urls)),
    url(r'^customers/', include(customer_urls)),
    url(r'^staff/', include(staff_urls)),
    url(r'^groups/', include(groups_urls)),
    url(r'^discounts/', include(discount_urls)),
    url(r'^settings/', include(site_urls)),
    url(r'^shipping/', include(shipping_urls)),
    url(r'^style-guide/', core_views.styleguide, name='styleguide'),
    url(r'^search/', include(search_urls)),
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import JavaScriptCatalog
from graphene_django.views import GraphQLView

from .account.urls import urlpatterns as account_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .search.urls import urlpatterns as search_urls

handler404 = 'saleor.core.views.handle_404'

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^cart/', include((cart_urls, 'cart'), namespace='cart')),
    url(r'^checkout/',
        include((checkout_urls, 'checkout'), namespace='checkout')),
    url(r'^dashboard/',
        include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^order/', include((order_urls, 'order'), namespace='order')),
    url(r'^products/',
        include((product_urls, 'product'), namespace='product')),
    url(r'^account/',
        include((account_urls, 'account'), namespace='account')),
    url(r'^feeds/',
        include((feed_urls, 'data_feeds'), namespace='data_feeds')),
    url(r'^search/', include((search_urls, 'search'), namespace='search')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls')),
    url('', include('social_django.urls', namespace='social'))]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)] + static(
            settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/search/forms.py
from ...search.backends import picker
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):
    def search(self):
        query = self.cleaned_data['q']
        search = picker.pick_dashboard_backend()
        return search(query)

saleor/dashboard/category/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Category
from ..views import staff_member_required
from .filters import CategoryFilter
from .forms import CategoryForm


@staff_member_required
@permission_required('product.view_category')
def category_list(request):
    categories = Category.tree.root_nodes().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'categories': categories, 'filter_set': category_filter,
        'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_create(request, root_pk=None):
    path = None
    category = Category()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form, 'path': path}
    return TemplateResponse(request, 'dashboard/category/form.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_edit(request, root_pk=None):
    path = None
    category = get_object_or_404(Category, pk=root_pk)
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Updated category %s') % category)
        if root_pk:
            return redirect('dashboard:category-detail', pk=root_pk)
        return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status, 'path': path}
    template = 'dashboard/category/form.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
@permission_required('product.view_category')
def category_detail(request, pk):
    root = get_object_or_404(Category, pk=pk)
    path = root.get_ancestors(include_self=True) if root else []
    categories = root.get_children().order_by('name')
    category_filter = CategoryFilter(request.GET, queryset=categories)
    categories = get_paginator_items(
        category_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {'categories': categories, 'path': path, 'root': root,
           'filter_set': category_filter,
           'is_empty': not category_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_category')
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(
            request,
            pgettext_lazy(
                'Dashboard message', 'Removed category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        if root_pk:
            if request.is_ajax():
                response = {'redirectUrl': reverse(
                    'dashboard:category-detail', kwargs={'pk': root_pk})}
                return JsonResponse(response)
            return redirect('dashboard:category-detail', pk=root_pk)
        else:
            if request.is_ajax():
                response = {'redirectUrl': reverse('dashboard:category-list')}
                return JsonResponse(response)
            return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(
        request, 'dashboard/category/modal/confirm_delete.html', ctx)

saleor/dashboard/collection/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.urls import reverse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...product.models import Collection
from ..views import staff_member_required
from .filters import CollectionFilter
from .forms import CollectionForm


@staff_member_required
@permission_required('product.view_product')
def collection_list(request):
    collections = Collection.objects.prefetch_related('products').all()
    collection_filter = CollectionFilter(request.GET, queryset=collections)
    collections = get_paginator_items(
        collection_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'collections': collections, 'filter_set': collection_filter,
        'is_empty': not collection_filter.queryset.exists()}
    return TemplateResponse(
        request, 'dashboard/collection/list.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def collection_create(request):
    collection = Collection()
    form = CollectionForm(request.POST or None, instance=collection)
    if form.is_valid():
        collection = form.save()
        msg = pgettext_lazy('Collection message', 'Added collection')
        messages.success(request, msg)
        return redirect('dashboard:collection-list')
    ctx = {'collection': collection, 'form': form}
    return TemplateResponse(request, 'dashboard/collection/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def collection_update(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    form = CollectionForm(request.POST or None, instance=collection)
    if form.is_valid():
        collection = form.save()
        msg = pgettext_lazy('Collection message', 'Updated collection')
        messages.success(request, msg)
        return redirect('dashboard:collection-update', pk=collection.pk)
    ctx = {'collection': collection, 'form': form}
    return TemplateResponse(request, 'dashboard/collection/detail.html', ctx)


@staff_member_required
@permission_required('product.edit_product')
def collection_delete(request, pk=None):
    collection = get_object_or_404(Collection, pk=pk)
    if request.method == 'POST':
        collection.delete()
        msg = pgettext_lazy('Collection message', 'Deleted collection')
        messages.success(request, msg)
        if request.is_ajax():
            response = {'redirectUrl': reverse('dashboard:collection-list')}
            return JsonResponse(response)
        return redirect('dashboard:collection-list')
    ctx = {'collection': collection}
    return TemplateResponse(
        request, 'dashboard/collection/confirm_delete.html', ctx)

saleor/dashboard/customer/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import pgettext_lazy

from ...core.utils import get_paginator_items
from ...account.models import User
from ..emails import send_set_password_email
from ..views import staff_member_required
from .filters import UserFilter
from .forms import CustomerForm


@staff_member_required
@permission_required('account.view_user')
def customer_list(request):
    customers = (
        User.objects
        .filter(
            Q(is_staff=False) | (Q(is_staff=True) & Q(orders__isnull=False)))
        .distinct()
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .order_by('email'))
    customer_filter = UserFilter(request.GET, queryset=customers)
    customers = get_paginator_items(
        customer_filter.qs, settings.DASHBOARD_PAGINATE_BY,
        request.GET.get('page'))
    ctx = {
        'customers': customers, 'filter_set': customer_filter,
        'is_empty': not customer_filter.queryset.exists()}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
@permission_required('account.view_user')
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related(
            'default_billing_address', 'default_shipping_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)


@staff_member_required
@permission_required('account.edit_user')
def customer_create(request):
    customer = User()
    form = CustomerForm(request.POST or None, instance=customer)
    if form.is_valid():
        form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Added customer %s' % customer)
        send_set_password_email(customer)
        messages.success(request, msg)
        return redirect('dashboard:customer-details', pk=customer.pk)
    ctx = {'form': form, 'customer': customer}
    return TemplateResponse(request, 'dashboard/customer/form.html', ctx)


@staff_member_required
@permission_required('account.edit_user')
def customer_edit(request, pk=None):
    customer = get_object_or_404(User, pk=pk)
    form = CustomerForm(request.POST or None, instance=customer)
    if form.is_valid():
        form.save()
        msg = pgettext_lazy(
            'Dashboard message', 'Updated customer %s' % customer)
        messages.success(request, msg)
        return redirect('dashboard:customer-details', pk=customer.pk)
    ctx = {'form': form, 'customer': customer}
    return TemplateResponse(request, 'dashboard/customer/form.html', ctx)

templates/dashboard/customer/detail.html
{% extends "dashboard/base.html" %}
{% load prices_i18n %}
{% load i18n %}
{% load materializecss %}
{% load status %}
{% load staticfiles %}

{% block title %}
  {{ customer }} - {% trans "Customers" context "Dashboard customers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:customers" as url %}
  {% include "dashboard/includes/_back_link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:customers" %}">
        {% trans "Customers" context "Dashboard customers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:customers" %}">
        <svg data-src="{% static "dashboard/images/arrow-left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li>
      <span class="breadcrumbs--elipsed-item">{{ customer }}</span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col m12 l8">
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ customer.email }}
          </span>
          <div class="row">
            {% if customer.date_joined %}
              <div class="col s12 m4 l12">
                <h4>
                  {% trans "Date joined" context "Customer field" %}
                </h4>
                <p>
                  {{ customer.date_joined }}
                </p>
              </div>
            {% endif %}
          </div>
        </div>
        <div class="card-action">
          {% if perms.account.edit_user %}
            <a href="{% url 'dashboard:customer-update' customer.pk %}" class="btn-flat waves-effect">
              {% trans "Edit customer" context "Customer action" %}
            </a>
          {% endif %}
          {% if perms.account.impersonate_user %}
            <a href="{% url 'impersonate-start' uid=customer.pk %}" class="btn-flat waves-effect">
              {% trans 'Impersonate customer' context 'Customer impersonate action' %}
            </a>
          {% endif %}
        </div>

      </div>

      <div class="card">
        <div class="data-table-header{% if not customer_orders %} data-table-header--no-data{% endif %}">
          <h5 class="data-table-title {% if not customer_orders %} data-table-title--no-data{% endif %}">
            {% trans "Recent orders" context "Customer recent orders table title" %}
          </h5>
        </div>
        {% if customer_orders %}
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  <th>
                    {% trans "Number" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Placed on" context "Customer orders table header" %}
                  </th>
                  <th>
                    {% trans "Order status" context "Customer orders table header" %}
                  </th>
                  <th class="right-align">
                    {% trans "Total" context "Customer orders table header" %}
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for order in customer_orders %}
                  <tr data-action-go="{% if perms.order.view_order %}{% url 'dashboard:order-details' order_pk=order.pk %}{% endif %}">
                    <td>
                      {{ order }}
                    </td>
                    <td>
                      {{ order.created }}
                    </td>
                    <td>
                      {% render_status order.status order.get_status_display %}
                    </td>
                    <td class="right-align">
                      {% gross order.total html=True %}
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <div class="card-content card-content--no-data">
            <p>
              {% trans "No orders found." context "Empty customer orders table message" %}
            </p>
          </div>
        {% endif %}
      </div>
    </div>


    <div class="col s12 l4">
       <div class="row">
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default shipping address" context "Customer default shipping address card title" %}
              </span>
              {% if customer.default_shipping_address %}
                {% with customer.default_shipping_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>{% trans "No default shipping address." context "Customer without default shipping address message" %}</div>
              {% endif %}
              <svg data-src="{% static "dashboard/images/email.svg" %}" width="14" height="14" />
              <a href="mailto:{{ customer.email }}">
                {{ customer.email }}
              </a>
            </div>
          </div>
        </div>
        <div class="col s12 m6 p6 l12">
          <div class="card equal-height-on-med">
            <div class="card-content">
              <span class="card-title black-text">
                {% trans "Default billing address" context "Customer default billing address card title" %}
              </span>
              {% if customer.default_billing_address %}
                {% with customer.default_billing_address as address %}
                  {% include 'dashboard/includes/_address.html' with address=address only %}
                {% endwith %}
              {% else %}
                <div>
                  {% trans "No default billing address." context "Customer without default billing address message" %}
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/customer/form.html
{% extends "dashboard/base.html" %}
{% load materializecss %}
{% load i18n %}
{% load staticfiles %}

{% block title %}
  {% if customer.pk %}
    {{ customer }}
  {% else %}
    {% trans "Add new customer" context "Dashboard add customer" %}
  {% endif %}
     - {% trans "Customer" context "Dashboard customer" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block header_menu %}
  {% url "dashboard:customers" as url %}
  {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--history">
    <li>
      <a href="{% url "dashboard:customers" %}">
        {% trans "Customers" context "Dashboard customers list" %}
      </a>
    </li>
    <li class="back-mobile">
      <a href="{% url "dashboard:customers" %}">
        <svg data-src="{% static "dashboard/images/arrow_left.svg" %}" fill="#fff" width="20px" height="20px" />
      </a>
    </li>
    <li><span class="breadcrumbs--elipsed-item">{% if customer.pk %}{{ customer }}{% else %}{% trans 'Add customer' context 'Dashboard add customer action' %}{% endif %}</span></li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l8">
      {% if form %}
        <form class="card" method="post">
          <div class="card-content">
            <span class="card-title">
              {% trans 'Customer details' context 'Customer details header' %}
            </span>
            <div class="data">
              {% csrf_token %}
              <div class="row">
                {{ form|materializecss }}
              </div>
            </div>
          </div>
          {% if perms.account.edit_user %}
          <div class="card-action right-align">
            {% if customer.pk %}
              <a href="{% url 'dashboard:customer-details' pk=customer.pk %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans 'Update' context 'Dashboard update action' %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:customers' %}" class="btn-flat waves-effect">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn waves-effect">
                {% trans 'Add' context 'Dashboard add action' %}
              </button>
            {% endif %}
          </div>
          {% endif %}
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/dashboard/customer/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load prices_i18n %}
{% load materializecss %}
{% load staticfiles %}
{% load utils %}

{% block title %}
  {% trans "Customers" context "Dashboard customers list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-customers{% endblock %}

{% block menu_customers_class %}active{% endblock %}

{% block header_extra %}
  {% if perms.account.edit_staff %}
    <div class="btn-fab-fixed">
      <a href="{% url 'dashboard:customer-create' %}" class="btn-fab-default waves-effect waves-light" title="{% trans "Add customer" context "Customer list add button text" %}" >
        <svg data-src="{% static "dashboard/images/add.svg" %}" />
      </a>
    </div>
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs">
    <li class="visible-s">
      {% trans "Customers" context "Dashboard customers list" %}
    </li>
  </ul>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12 l9">
      {% if customers %}
        <div class="card">
          <div class="data-table-container">
            <table class="bordered highlight responsive data-table">
              <thead>
                <tr>
                  {% trans "Name" context "Customers table header" as label %}
                  {% sorting_header 'name' label %}

                  {% trans "Email" context "Customers table header" as label %}
                  {% sorting_header 'email' label %}

                  {% trans "Location" context "Customers table header" as label %}
                  {% sorting_header 'location' label %}
                </tr>
              </thead>
              <tbody>
                {% for customer in customers %}
                  <tr data-action-go="{% url "dashboard:customer-details" pk=customer.pk %}">
                    {% with customer.default_billing_address as default_address %}
                      <td>
                        {% if default_address %}
                          {{ default_address.first_name }} {{ default_address.last_name }}
                        {% else %}
                          -
                        {% endif %}
                      </td>
                      <td>
                        {{ customer.email }}
                      </td>
                      <td>
                        {% if default_address %}
                          {{ default_address.city }}, {{ default_address.get_country_display }}
                        {% else %}
                          -
                        {% endif %}
                      </td>
                    {% endwith %}
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        {% paginate customers %}
      {% else %}
        {% if is_empty %}
          {% include 'dashboard/customer/zero_page.html' %}
        {% else %}
          <div class="col s12">
            <div class="not-found">
              <p class="grey-text">
                {% trans "No customers found." context "Empty customers table message" %}
              </p>
            </div>
          </div>
        {% endif %}
      {% endif %}
    </div>
    <div class="col s12 l3" id="filters">
      {% if not is_empty %}{% filters filter_set %}{% endif %}
    </div>
  </div>
{% endblock %}

templates/dashboard/customer/zero_page.html
{% extends 'dashboard/base_zero_page.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "No customers found." %}{% endblock %}
{% block content %}
  {% static "dashboard/images/add.svg" as img_path %}
  {% blocktrans %}
    Customer accounts will appear here once users register in the shop.
  {% endblocktrans %}
{% endblock %}